version: 0.2

env:
  variables:
    WEBSITE_BUCKET: "lnybro.dk"
    YOUR_CLOUDFRONT_DISTRIBUTION_ID: "E24JYCZMYW08WU"
    
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Installing dependencies..."
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo "Building React TypeScript app..."
      - yarn build

  post_build:
    commands:
      - echo "Syncing build files to S3..."
      - aws s3 sync build/ s3://${WEBSITE_BUCKET}/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ${YOUR_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"